### ISSUE TITLE
Enable ESM support for all or add separate entries

### ISSUE THREAD

**Issue by searchableguy** [grissius/jest-is-a-rude-needy-clown-and-eats-lot-of-memory#1]
I noticed you aren't using esm with jest while it is turned on by default for vite.

There are several changes introduced by ES modules which affect how long tests will take to setup so it's not a fair comparison of tools.

**Comment by smolijar** [comment]
Hi, not all frameworks support ESM by default, but fair point about skewed results. Feel free to make Vitest work with CommonJS if you are able to. I wasn't.

**Comment by searchableguy** [comment]
I think a note would be good to add. For jest at least, you can enable the experimental ESM support. 

If not, I recommend enabling globals and disabling isolation option in vite. That will make it on par with jest.

https://vitest.dev/config/#isolate
https://vitest.dev/config/#globals

**Comment by smolijar** [comment]
If you really think that is the issue, `globals` seems to be fair (even though it might not reflect the performance regression to expect when you migrate from default config to default config which will be the case for many users).

`isolate` is completely unreasonable, it introduces lot of overhead atop of ESM and the suite isolation and module cache tricks is in fact the main cause of issues with Jest performance as far as I can tell. Jest does not allow to disable it either.

I ran some of the tests with globals.

[Many tests](https://github.com/grissius/jest-is-a-rude-needy-clown-and-eats-lot-of-memory#many-tests)
```
	Command being timed: "npm run vitest"
	Elapsed (wall clock) time (h:mm:ss or m:ss): 3:10.37
	Maximum resident set size (kbytes): 433924
```

[Concurrent tests](https://github.com/grissius/jest-is-a-rude-needy-clown-and-eats-lot-of-memory#concurrent-tests) `--no-threads` variant
```
	Command being timed: "npm run vitest -- --no-threads"
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:53.79
	Maximum resident set size (kbytes): 439264
```

Frankly the results are not that much different so I still think that the data is still relevant. I did not bother to run the rest.

**Comment by searchableguy** [comment]
I was talking about disabling isolate for vite. Jest by default not have an isolate worker thread for each file. It uses VM context. 

Try running vite with --no-isolate flag or change it from the config. 

Although including the no-isolate result wouldn't be great because on surface, jest and vite both are trying to achieve the same result but with different isolation strategies. 

I'm just curious if that is the main reason behind performance bottleneck here.

**Comment by smolijar** [comment]
> I was talking about disabling isolate for vite. Jest by default not have an isolate worker thread for each file. It uses VM context.

1. Please provide a citation to support this claim. I don't agree that Jest does not provide a suite isolation, because I believe it is the very reason of the memory leaks described in https://github.com/grissius/jest-is-a-rude-needy-clown-and-eats-lot-of-memory#leakables
2. I know what you were talking about, as I said, I don't think it's fair. It does not have anything to do with ESM as you pointed out earlier. The fact is that with default config, Vitest fails to beat Jest in performance in various tests, regarding both time and memory. We don't have anyone to advocate for Jest to tweak all possible options to perform better either. If you switch from Jest to Vitest, you are to expect some performance regression based on these scenarios (I've seen benchmarks where Vitest outperforms Jest in the watch mode for example, good for you I guess). Period. I don't claim that you cannot make it better with some config.
3. I think the tests are fair, default config, same environment (all commonJS imports now). If this keeps bothering you, feel free to make some effort as well. Run the tests on your end, configure the hell out of Vitest to make it look better, I will be glad to link  your findings, but frankly I don't care that much.
